# Generated by Django 4.1.13 on 2025-07-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_category_image_url_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
    ]
